webtalk_init -webtalk_dir /home/rupprich/Zynq/indoor-loc/indoor-loc.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Dec 15 15:33:15 2015" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2015.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2015.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "r7u0csua1jqu598m53v6l21qrd" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2015.3_10" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "10" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "" -context "user_environment"
webtalk_add_data -client project -key os_release -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1450169279000" -context "sdk\\\\bsp/1450169279000"
webtalk_add_data -client sdk -key hwid -value "1445952707000" -context "sdk\\\\bsp/1450169279000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1450169279000"
webtalk_add_data -client sdk -key apptemplate -value "null" -context "sdk\\\\bsp/1450169279000"
webtalk_add_data -client sdk -key uid -value "1450189581000" -context "sdk\\\\bsp/1450189581000"
webtalk_add_data -client sdk -key hwid -value "1445952707000" -context "sdk\\\\bsp/1450189581000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1450189581000"
webtalk_add_data -client sdk -key apptemplate -value "null" -context "sdk\\\\bsp/1450189581000"
webtalk_transmit -clientid 1975471324 -regid "" -xml /home/rupprich/Zynq/indoor-loc/indoor-loc.sdk/webtalk/usage_statistics_ext_sdk.xml -html /home/rupprich/Zynq/indoor-loc/indoor-loc.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /home/rupprich/Zynq/indoor-loc/indoor-loc.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
