webtalk_init -webtalk_dir /home/rupprich/Zynq/indoor-loc-zybo/indoor-loc-zybo.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Oct 27 11:56:31 2015" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2015.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2015.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "pmvahk9jfn3h0oe9tieh17493a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2015.3_5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "5" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "" -context "user_environment"
webtalk_add_data -client project -key os_release -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1445935571000" -context "sdk\\\\bsp/1445935571000"
webtalk_add_data -client sdk -key hwid -value "1445865577000" -context "sdk\\\\bsp/1445935571000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1445935571000"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\bsp/1445935571000"
webtalk_add_data -client sdk -key uid -value "1445935572000" -context "sdk\\\\application/1445935572000"
webtalk_add_data -client sdk -key hwid -value "1445865577000" -context "sdk\\\\application/1445935572000"
webtalk_add_data -client sdk -key bspid -value "1445935571000" -context "sdk\\\\application/1445935572000"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1445935572000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1445935572000"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1445935572000"
webtalk_add_data -client sdk -key uid -value "1445935689000" -context "sdk\\\\bsp/1445935689000"
webtalk_add_data -client sdk -key hwid -value "1445865577000" -context "sdk\\\\bsp/1445935689000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1445935689000"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\bsp/1445935689000"
webtalk_add_data -client sdk -key uid -value "1445935690000" -context "sdk\\\\application/1445935690000"
webtalk_add_data -client sdk -key hwid -value "1445865577000" -context "sdk\\\\application/1445935690000"
webtalk_add_data -client sdk -key bspid -value "1445935689000" -context "sdk\\\\application/1445935690000"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1445935690000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1445935690000"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1445935690000"
webtalk_transmit -clientid 2968527326 -regid "" -xml /home/rupprich/Zynq/indoor-loc-zybo/indoor-loc-zybo.sdk/webtalk/usage_statistics_ext_sdk.xml -html /home/rupprich/Zynq/indoor-loc-zybo/indoor-loc-zybo.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /home/rupprich/Zynq/indoor-loc-zybo/indoor-loc-zybo.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
