## PWM Pins --> JB0..5
#set_property PACKAGE_PIN W12 [get_ports {pwmPulse[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {pwmPulse[0]}]
#set_property PACKAGE_PIN W11 [get_ports {pwmPulse[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {pwmPulse[1]}]
#set_property PACKAGE_PIN V10 [get_ports {pwmPulse[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {pwmPulse[2]}]
#set_property PACKAGE_PIN W8 [get_ports {pwmPulse[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {pwmPulse[3]}]
#set_property PACKAGE_PIN V12 [get_ports {pwmPulse[4]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {pwmPulse[4]}]
#set_property PACKAGE_PIN W10 [get_ports {pwmPulse[5]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {pwmPulse[5]}]


# ----------------------------------------------------------------------------
# User LEDs - Bank 33
# ----------------------------------------------------------------------------
set_property PACKAGE_PIN T22 [get_ports {pwmPulse[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwmPulse[0]}]
set_property PACKAGE_PIN T21 [get_ports {pwmPulse[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwmPulse[1]}]
set_property PACKAGE_PIN U22 [get_ports {pwmPulse[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwmPulse[2]}]
set_property PACKAGE_PIN U21 [get_ports {pwmPulse[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwmPulse[3]}]
set_property PACKAGE_PIN V22 [get_ports {pwmPulse[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwmPulse[4]}]
set_property PACKAGE_PIN W22 [get_ports {pwmPulse[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwmPulse[5]}]


create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 131072 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list design_1_i/processing_system7_0/inst/FCLK_CLK0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 1 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {design_1_i/pwm_0/pwmPulse[0]}]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK0]
