webtalk_init -webtalk_dir /home/rupprich/Zynq/indoor-loc-zybo/indoor-loc-zybo.hw/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Oct 27 12:09:50 2015" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "Vivado v2015.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1368829" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "174144604_174870429_208900094_202" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "749b3db493815e208dcb5cd85f9071e6" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "9d6357aa-0979-458a-ac2c-27de7c1b2c18" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "unknown" -context "user_environment"
webtalk_add_data -client project -key os_release -value "unknown" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7 CPU       M 620  @ 2.67GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2667.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_add_data -client project -key os_name -value "unknown" -context "user_environment"
webtalk_add_data -client project -key os_release -value "unknown" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7 CPU       M 620  @ 2.67GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2667.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client labtool
webtalk_add_data -client labtool -key pgmcnt -value "00:00:00" -context "labtool\\usage"
webtalk_add_data -client labtool -key cable -value "" -context "labtool\\usage"
webtalk_add_data -client labtool -key cable -value "" -context "labtool\\usage"
webtalk_transmit -clientid 4230973586 -regid "174144604_174870429_208900094_202" -xml /home/rupprich/Zynq/indoor-loc-zybo/indoor-loc-zybo.hw/webtalk/usage_statistics_ext_labtool.xml -html /home/rupprich/Zynq/indoor-loc-zybo/indoor-loc-zybo.hw/webtalk/usage_statistics_ext_labtool.html -wdm /home/rupprich/Zynq/indoor-loc-zybo/indoor-loc-zybo.hw/webtalk/usage_statistics_ext_labtool.wdm -intro "<H3>LABTOOL Usage Report</H3><BR>"
webtalk_terminate
